Creating Tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.5.1


In [4]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([3])

In [12]:
# Matrix
matrix = torch.tensor([[1, 2], 
                       [5, 6]])
matrix

tensor([[1, 2],
        [5, 6]])

In [14]:
matrix.ndim

2

In [15]:
matrix[1]

tensor([5, 6])

In [16]:
matrix[0]

tensor([1, 2])

In [17]:
matrix.shape

torch.Size([2, 2])

In [19]:
# Tensor
tensor = torch.tensor([[[1, 2], 
                         [3, 4]]])

tensor

tensor([[[1, 2],
         [3, 4]]])

In [20]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([1, 2, 2])