Creating Tensors

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.5.1


In [4]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
# Get tensor back as Python int
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([3])

In [10]:
# Matrix
MATRIX = torch.tensor([[1, 2], 
                       [5, 6]])
MATRIX

tensor([[1, 2],
        [5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([5, 6])

In [13]:
MATRIX[0]

tensor([1, 2])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2], 
                         [3, 4]]])

TENSOR

tensor([[[1, 2],
         [3, 4]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 2, 2])

In [18]:
TENSOR[0]

tensor([[1, 2],
        [3, 4]])

In [19]:
TENSOR1 = torch.tensor([[[[1,2],[3,4]]]])

In [20]:
TENSOR1.ndim

4

In [21]:
TENSOR1.shape

torch.Size([1, 1, 2, 2])

In [22]:
TENSOR1[0]

tensor([[[1, 2],
         [3, 4]]])