Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [2]:
import torch

In [3]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
# Print the tensor
print(random_tensor)

tensor([[0.1019, 0.3905, 0.7412, 0.8513],
        [0.4728, 0.8430, 0.5827, 0.0500],
        [0.0912, 0.4245, 0.3926, 0.0754]])


In [5]:
torch.rand(1, 2, 2)

tensor([[[0.7622, 0.1927],
         [0.8940, 0.6976]]])

In [8]:
torch.rand(2, 2, 2)

tensor([[[0.2316, 0.3806],
         [0.6453, 0.6029]],

        [[0.6387, 0.8238],
         [0.1723, 0.4966]]])