Create a range of tensors and tensors-like

In [2]:
import torch

In [3]:
torch.range(0,10)

C:\Users\N I T R O V15\AppData\Local\Temp\ipykernel_9220\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
one_to_ten = torch.arange(1, 11)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [6]:
 another = torch.arange(0, 1000, 77)
print(another)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [7]:
# Creating tensors like
one_to_ten = torch.arange(1, 11)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [8]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
