Note : Tensor datatypes is one of the 3 big errors you will run into with Pytorch and deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [2]:
import torch

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None)
float_32_tensor

tensor([1., 2., 3.])

In [4]:
float_32_tensor.dtype  # Should be torch.float32

torch.float32

In [6]:
float_16_tensor = float_32_tensor.to(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [5]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor.dtype  # Should be torch.float16

torch.float16

In [8]:
mul = float_16_tensor * float_32_tensor  # Implicit conversion to float32
mul

tensor([1., 4., 9.])

In [11]:
mul.dtype

torch.float32

In [12]:

float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, # what datatype is tensor
device = None, # what device is tensor on
requires_grad = False # whether to track gradients
)
float_32_tensor

tensor([1., 2., 3.])