In [1]:
import torch

In [2]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [4]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

In [5]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

Getting information from tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [6]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7377, 0.2202, 0.4637, 0.2542],
        [0.5903, 0.7060, 0.3239, 0.3936],
        [0.9509, 0.0549, 0.4644, 0.4531]])

In [7]:
# Find out details about some tensor
print(some_tensor)
print(f"Data type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.7377, 0.2202, 0.4637, 0.2542],
        [0.5903, 0.7060, 0.3239, 0.3936],
        [0.9509, 0.0549, 0.4644, 0.4531]])
Data type: torch.float32
Shape: torch.Size([3, 4])
Device: cpu
