Manipulating Tensors

Tensor operations include :
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [2]:
import torch

In [3]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [6]:
tensor = tensor * 10
tensor

tensor([100, 200, 300])

In [7]:
tensor - 20

tensor([ 80, 180, 280])

In [8]:
# Pytorch inbuilt functions
tensor = torch.tensor([1,2,3])
tensor.add(10)

tensor([11, 12, 13])

In [9]:
tensor.mul(10)

tensor([10, 20, 30])

In [10]:
tensor.div(10)

tensor([0.1000, 0.2000, 0.3000])