Two main ways of performing multiplication in neural networks and deep learning.
- Element-wise multiplication 
- Matrix multiplication (dot product)

In [1]:
import torch

In [2]:
tensor = torch.tensor([1, 2, 3])

In [3]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Result: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Result: tensor([1, 4, 9])


In [4]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [5]:
tensor

tensor([1, 2, 3])

In [9]:
# Matrix multiplication by hand
print(tensor[0] * tensor[0] + tensor[1] * tensor[1] + tensor[2] * tensor[2])

tensor(14)


In [10]:
1 * 1 + 2 * 2 + 3 * 3

14

In [13]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [14]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)

One of the most common errors in deep learning is shape errors

There are two main   rules that performing matrix multiplication needs to satisfy:
1. The inner dimensions must match:


In [15]:
torch.rand(3,2)

tensor([[0.3478, 0.1102],
        [0.7716, 0.5761],
        [0.2107, 0.4775]])

In [16]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [17]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3444, 0.8336, 0.3816],
        [0.3141, 0.2131, 0.2324],
        [0.0465, 0.5476, 0.1435]])

In [18]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)