Binary Classification: forward pass

In [4]:
import torch
import torch.nn as nn

In [5]:
# Create input data of shape 5*6
input_data = torch.tensor(
    [[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
     [0.4838, 0.4001, 0.9786, 0.7858, 0.9876, 0.5987],
     [0.1902, 0.8507, 0.8175, 0.0994, 0.3862, 0.0132],
     [0.1973, 0.6625, 0.8123, 0.4483, 0.0345, 0.4165],
     [0.6948, 0.3557, 0.7689, 0.2793, 0.6816, 0.9152]]
)

In [6]:
# Create binary classification model
model = nn.Sequential(
    nn.Linear(6,4), # First linear layer
    nn.Linear(4,1), # Second linear layer
    nn.Sigmoid() # Sigmoid activation function
)

# Pass input data through model
output = model(input_data)

In [9]:
print(output) 
# Ouputs are five probabilities between 0 and 1
# It gives one value for each sample(row) in data

# Classification
# Class = 0 for first and third values
# Class = 1 for second, fourth and fifth values

tensor([[0.4784],
        [0.5069],
        [0.4938],
        [0.5128],
        [0.5496]], grad_fn=<SigmoidBackward0>)


In [12]:
# Specify model has three classes
n_classes = 3

# Create multi-class classification model
model = nn.Sequential(
    nn.Linear(6,4), # First linear layer
    nn.Linear(4,n_classes), # Second linear layer
    nn.Softmax(dim = -1) # Softmax activation function
)

# Pass input data through model
output = model(input_data)
print(output.shape) # Output shape is 5*3

torch.Size([5, 3])


In [14]:
print(output)

# Each row sums to one
# Value with highest probability is assigned predicted label in each row

tensor([[0.3329, 0.4369, 0.2301],
        [0.4274, 0.3355, 0.2372],
        [0.3673, 0.3925, 0.2402],
        [0.3848, 0.3712, 0.2440],
        [0.3827, 0.4066, 0.2107]], grad_fn=<SoftmaxBackward0>)


In [16]:
# Regression : Forwards pass

# Create regression model
model = nn.Sequential(
    nn.Linear(6,4), # First linear layer
    nn.Linear(4,1) # Second linear layer
)

# Pass input data through model
output = model(input_data)

print(output)

tensor([[-0.7252],
        [-0.6163],
        [-0.4906],
        [-0.4815],
        [-0.4589]], grad_fn=<AddmmBackward0>)


#### Building a binary classifier in PyTorch

Recall that a small neural network with a single linear layer followed by a sigmoid function is a binary classifier. It acts just like a logistic regression.

In this exercise, you'll practice building this small network and interpreting the output of the classifier.

In [20]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8,1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.3666]], grad_fn=<SigmoidBackward0>)


In [22]:
# Regression model

import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 2),
    nn.Linear(2, 1)
    )

output = model(input_tensor)
print(output)

tensor([[0.3232]], grad_fn=<AddmmBackward0>)


In [27]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim = -1)
)

output = model(input_tensor)
print(output)

tensor([[0.2024, 0.1958, 0.3086, 0.2932]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# OHE Manually
import numpy as np
one_hot_numpy = np.array([1,0,0])

In [30]:
# Prevent doing manually

import torch.nn.functional as f
f.one_hot(torch.tensor(0), num_classes = 3)

tensor([1, 0, 0])

In [31]:
f.one_hot(torch.tensor(1), num_classes = 3)

tensor([0, 1, 0])

In [33]:
f.one_hot(torch.tensor(2), num_classes = 3)

tensor([0, 0, 1])

In [35]:
# Cross Entropy Loss in PyTorch
import torch
from torch.nn import CrossEntropyLoss

scores = torch.tensor([[-0.1211, 0.1059]])
one_hot_target = torch.tensor([[1,0]])

criterion = CrossEntropyLoss()
criterion(scores.double(), one_hot_target.double())

tensor(0.8131, dtype=torch.float64)