#### Machine learning vs. deep learning

Machine learning and deep learning can both be described as artificial intelligence. In both cases, a computer system learns from data to make intelligent decisions. However, deep learning diverges from machine learning in many different aspects.

Traditional Machine Learning
- Typically does not require a GPU
- Typically relies on hand-crafted feature engineering
- Requires relatively less data

Deep Learning
- Models have a lot of parameters
- Often requires a GPU
- Can learn features from large, unstructured data

In [2]:
import torch
lst = [[1,2,3],[4,5,6]]
tensor = torch.tensor(lst)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
import numpy as np
array = [1,2,3,4]
np_array = np.array(array)
np_tensor = torch.tensor(np_array)
print(np_tensor)

tensor([1, 2, 3, 4], dtype=torch.int32)


In [5]:
lst = [[1,2,3],[4,5,6]]
tensor = torch.tensor(lst)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [6]:
# Compatible shapes
a = torch.tensor([[1,1],
                  [2,2]])
b = torch.tensor([[2,2],
                 [3,3]])
print(a+b)
print(torch.add(a,b))

print(a-b)
print(torch.sub(a,b))

print(a*b)
print(torch.mul(a,b))

tensor([[3, 3],
        [5, 5]])
tensor([[3, 3],
        [5, 5]])
tensor([[-1, -1],
        [-1, -1]])
tensor([[-1, -1],
        [-1, -1]])
tensor([[2, 2],
        [6, 6]])
tensor([[2, 2],
        [6, 6]])


In [8]:
# Incompatible shapes which gives error
a = torch.tensor([[1,1],
                  [2,2]])
c = torch.tensor([[2,2,4],
                  [3,3,5]])
print(a+c)


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

##### Creating tensors and accessing attributes

Tensors are the primary data structure in PyTorch and will be the building blocks for our deep learning models. They share many similarities with NumPy arrays but have some unique attributes too.

In this exercise, you'll practice creating a tensor from a Python list and displaying some of its attributes.

In [9]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

tensor([1, 2, 3, 4])


In [11]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


#### Creating tensors from NumPy arrays

Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.

In [12]:
import numpy as np
array_a = np.array([[1,1,1],
                    [2,3,4],
                    [4,5,6]])
array_b = np.array([[7,5,4],
                   [2,2,8],
                   [6,3,8]])

In [13]:
# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]], dtype=torch.int32)


In [14]:
import torch.nn as nn

# Create input_tensor with three features
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]]
)

# A linear layer takes an input, applies a linear function and returns the output

# Define our first linear layer
linear_layer = nn.Linear(in_features = 3, out_features = 2)

# Pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[0.2839, 0.2779]], grad_fn=<AddmmBackward0>)


In [15]:
linear_layer.weight

Parameter containing:
tensor([[-0.3839, -0.1537, -0.1121],
        [ 0.0429,  0.2808, -0.0013]], requires_grad=True)

In [16]:
linear_layer.bias

Parameter containing:
tensor([0.4607, 0.1351], requires_grad=True)

In [17]:
# Create network with three linear layers
model = nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)

input_tensor = torch.tensor([[-0.0014, 0.4038, 1.0305, 0.7521, 0.2942, -0.8694, 0.3132, 0.1351, -0.7585, 0.2893]])

# Pass input_tensor through model to get output
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[ 0.3472, -0.0120,  0.0420, -0.0964,  0.1605]],
       grad_fn=<AddmmBackward0>)


#### Your first neural network

In this exercise, you will implement a small neural network containing two linear layers. The first layer takes an eight-dimensional input, and the last layer outputs a one-dimensional tensor.

In [18]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 5),
    nn.Linear(5, 1)
)

output = model(input_tensor)
print(output)

tensor([[-1.2069]], grad_fn=<AddmmBackward0>)


In [19]:
# Sigmoid Function
import torch
import torch.nn as nn

input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9975]])


In [20]:
# Activation Function as last layer
model = nn.Sequential(
    nn.Linear(6,4), # First Linear Layer
    nn.Linear(4,1), # Second Linear Layer
    nn.Sigmoid() # Sigmoid Activation Function
)

In [21]:
## Getting familiar with softmax
import torch
import torch.nn as nn

# Create an input tensor
input_tensor = torch.tensor(
    [[4.3, 6.1, 2.3]]
)

# Apply softmax along the last dimension
probabilities = nn.Softmax(dim = -1) # dim = -1 indicates softmax is applied to the input tensor's last dimension 
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


#### The sigmoid and softmax functions

The sigmoid and softmax functions are two of the most popular activation functions in deep learning. They are both usually used as the last step of a neural network. Sigmoid functions are used for binary classification problems, whereas softmax functions are often used for multi-class classification problems. This exercise will familiarize you with creating and using both functions.

In [22]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [23]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim = -1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])
